---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-web-svc-port
