---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Release.Name }}
spec:
  entrypoint: only-entrypoint
  templates:
  - name: only-entrypoint
    container:
      name: {{ .Release.Name }}
      command: ["python"]
      args: ["main.py"]
      image: {{ include "server.image" . }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - containerPort: 80
          name: http-svc-port
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: RUNNING_IN_CLUSTER
          value: true
    imagePullSecrets:
    - name: gcr-json-key
